<a href="https://colab.research.google.com/github/Sainithinkadarla/Learn_AI/blob/main/Pytorch_tutorial_freecodecamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tutorial

## PyTorch Fundamentals


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to tensors
### Creating tensors

In [4]:
# scalar

scalar  = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
vector[1]

tensor(7)

In [11]:
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [12]:
MATRIX[1]

tensor([3, 4])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
# Tensor

TENSOR2 = torch.tensor([[[1,2,3],[4,5,6],[4,5,6],[7,8,9]]])
TENSOR2

tensor([[[1, 2, 3],
         [4, 5, 6],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR2.ndim


3

In [20]:
TENSOR2.shape

torch.Size([1, 4, 3])

In [21]:
print(TENSOR2[0],"\n------------------------------------------\n",TENSOR2[0,1],"\n------------------------------------------\n",TENSOR2[0,1,2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [7, 8, 9]]) 
------------------------------------------
 tensor([4, 5, 6]) 
------------------------------------------
 tensor(6)


### Random Tensors

  Why random tensors

  Random tensors are important because the way neural netowrks learn is that they start with tensors full of random numbers and then adjust thise random numbers to bettter represent the data

  `start with random numbers -> look at data -> update random numbers -> look at data -> again update random numbers`

In [22]:
# Creating the random tensor of suize(3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8348, 0.8887, 0.4872, 0.7204],
        [0.6667, 0.5998, 0.6455, 0.1720],
        [0.6049, 0.6218, 0.0020, 0.4425]])

In [23]:
random_tensor.ndim

2

In [24]:
# Creating a random tensor which similar to image tensor
random_image_tensor = torch.rand((244,244,3))
random_image_tensor.shape, "shape \nndim ",random_image_tensor.ndim

(torch.Size([244, 244, 3]), 'shape \nndim ', 3)

### Zeros and Ones

In [28]:
zeros = torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

In [33]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [39]:
one_to_ten = torch.arange(1,11)
even = torch.arange(2,11,2)

one_to_ten, even

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 2,  4,  6,  8, 10]))

In [50]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_ones = torch.ones_like(ten_zeros)

ten_zeros,ten_ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into pytorch & deep learning:
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

In [55]:
# Float32 tensor

f32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None)
f16_tensor = torch.tensor([3.0,6.0,9.0],dtype = torch.float16)

f_other_options = torch.tensor([3,2,1,1], dtype=None, device=None, requires_grad= False)

f32_tensor, f32_tensor.dtype, f16_tensor, f16_tensor.dtype

(tensor([3., 6., 9.]),
 torch.float32,
 tensor([3., 6., 9.], dtype=torch.float16),
 torch.float16)

In [58]:
exp_f16_tensor = f32_tensor.type(torch.half)
exp_f16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [60]:
exp_f16_tensor * f32_tensor

tensor([ 9., 36., 81.])

In [62]:
i32_tensor = torch.tensor([1,2,34], dtype= torch.int32)

In [64]:
exp_f16_tensor * i32_tensor

tensor([  3.,  12., 306.], dtype=torch.float16)

In [67]:
long_tensor = torch.tensor([1,2,3], dtype= torch.long)

exp_f16_tensor * long_tensor

tensor([ 3., 12., 27.], dtype=torch.float16)


### Getting information from tensors

  1. Shape
  2. Dtype
  3. Device

In [68]:
test = torch.tensor([1,2,3])
test

tensor([1, 2, 3])

In [70]:
print(f"shape : {test.shape} \ndtype : {test.dtype}\ndevice : {test.device}")

shape : torch.Size([3]) 
dtype : torch.int64
device : cpu


### Manipulating tensors

Tensors operations like:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [75]:
tensor = torch.tensor([1,2,3])
tensor, tensor+10, tensor*10, tensor - 10

(tensor([1, 2, 3]),
 tensor([11, 12, 13]),
 tensor([10, 20, 30]),
 tensor([-9, -8, -7]))

In [77]:
# Tryin PyTorch in-bulit functions
torch.mul(tensor, 10 )

tensor([10, 20, 30])

In [78]:
torch.add(tensor, 10 )

tensor([11, 12, 13])